### ISSUE TITLE
Regarding the progress of the work

### ISSUE THREAD

**Issue by flashmoment** [cviviers/YOLOv5-6D-Pose#10]
I am sorry to bother you again, when will the multi-object detection be available?

**Comment by cviviers** [comment]
Hey @flashmoment,

No problem, the code for training multi-object pose estimation already works in the current version (testing needs to be updated). I am writing up a new paper for the multi-object pose estimation so it can still take some time before it is done, but I will see if I can release the code earlier (maybe without weights etc.). 

Short answer: 1 month for code (as soon as I have time), 4-5 months for weights.

**Comment by flashmoment** [comment]
> Hey @flashmoment,
> 
> No problem, the code for training multi-object pose estimation already works in the current version (testing needs to be updated). I am writing up a new paper for the multi-object pose estimation so it can still take some time before it is done, but I will see if I can release the code earlier (maybe without weights etc.).
> 
> Short answer: 1 month for code (as soon as I have time), 4-5 months for weights.

thank you very much
