### ISSUE TITLE
Pls I'm running the train program got an error like this

### ISSUE THREAD

**Issue by panwenfeics26** [cviviers/YOLOv5-6D-Pose#12]
! [WeChat screenshot_20240622195335] (https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/2e862485-36bc-43ef-aad3-618fdce57784)
! [WeChat screenshot_20240622195354] (https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/cd4d5510-5831-406b-bfd7-f77b4e971525)
! [WeChat screenshot_20240622195414] (https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/88722cf6-315a-4229-b57a-8bea130e78bb)
Is there anything wrong with this, please？

**Comment by cviviers** [comment]
Hey @panwenfeics26,

Try deleting the .cache files and running again. It will tell you what is wrong when trying to load the labels.

**Comment by panwenfeics26** [comment]
Thank you very much for your guidance, I've found the problem, adopted your updated linemod dataset, thank you very much
