### ISSUE TITLE
I can't get your results on the linmod dataset

### ISSUE THREAD

**Issue by panwenfeics26** [cviviers/YOLOv5-6D-Pose#14]
I'm trying to train your model, but the trained model doesn't predict the outcome
The command I used was python train.py --batch 32 --epochs 5000 --cfg yolov5xv6_pose_bifpn.yaml --hyp configs/hyp.single.yaml --weights yolov5x.pt --data configs/linemod/benchvise.yaml --rect --cache --optimizer Adam 

Here are my training parameters
![微信截图_20240626160541](https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/df9d2047-4d93-43b8-b322-f9e0d7ad9133)

I used cat data for training, but the training model could not detect any coordinates in the previous many images when reasoning
![微信截图_20240626160755](https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/0f97528f-30e8-429e-8ebd-c0b43864fad4)
 
The picture that can detect the coordinates, the coordinates are also very inaccurate can you tell me what is wrong with the training? Thank you very much for your answer
![微信截图_20240626161033](https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/771758e6-2d86-4ec7-8f1a-3fa3d1bd4f4e)

Here are some pictures from my training
![微信截图_20240626162359](https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/7c29e920-a0ad-4c45-997e-a45cf66578be)
![微信截图_20240626162436](https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/6a9e800d-b7bc-4887-9a62-a59d4fc19778)

**Comment by cviviers** [comment]
Hi @panwenfeics26,

The params look correct. Are you also training with replacing the background and occluding the objects? These parameters are set in the config file, which should work correctly if the VOC dataset is set up correctly.

Here are is my output from the cat run:

![results](https://github.com/cviviers/YOLOv5-6D-Pose/assets/20801247/704b52ee-3cc9-4766-afbf-f883a0023a75)

**Comment by panwenfeics26** [comment]
Thank you very much for your answer, I have been able to train the model normally. Thank you for such a great job.
