### ISSUE TITLE
About testing the effects under the Occlusion LineMod data set

### ISSUE THREAD

**Issue by panwenfeics26** [cviviers/YOLOv5-6D-Pose#15]
Hello, I want to test the effect of your model on the "Occlusion LineMod" data set. I notice that your data contains the labels_occlusion label. Is this the real label used to test the "Occlusion LineMod" data set? Do the mesh vertices corners3D etc. in your code need to be modified?

I look forward to your reply. Thank you very much

**Comment by cviviers** [comment]
Hi @panwenfeics26,

yes, those should be the occlusion test labels. I have not used them yet but I think it will be straightforward updating them and running the pretrained models on the occlusion objects. I think all you need to do is append the camera parameters (as provided in the linemod update script in the repo) to the label files and it should work.

**Comment by panwenfeics26** [comment]
Thanks for your answer, now I am making my own pose estimation data. I used ObjectDataSetTools to get a simple pose estimation data set, but found that the estimation effect is not good, can I build it according to your tutorial?

Below are some pictures I made and the estimated results. However, due to the shooting Angle, the production data set cannot extract the features of each view Angle of the object well. Do I need to make them according to your method?
![GIF 2024-7-5 20-58-10](https://github.com/cviviers/YOLOv5-6D-Pose/assets/103551465/ca357213-f5af-4c8f-bd3a-70bae701043f)

You can see that when I flip the object, I don't detect it very well

**Comment by cviviers** [comment]
Can you maybe acquire more images of the object at different angles? maybe flip the object and corresponding 3D model. My method of acquiring data is based on similar principles as the method you are already using.

**Comment by panwenfeics26** [comment]
Unfortunately, when making the data set, it is impossible to move. I do not know how to collect the pose information from different viewing angles, and the pose of the object cannot be detected from the missing viewing Angle

**Comment by cviviers** [comment]
Can you not collect 1 dataset with the object in its normal position and 1 when the object is tilted and combine them randomly?
