### ISSUE TITLE
How to modify my code if I don't have a segmentation Mask Folder

### ISSUE THREAD

**Issue by tongfengqi** [cviviers/YOLOv5-6D-Pose#16]
I noticed that the segmentation Masks Folder is Optional, if I don't have a Segmentation Mask Folder, how should I modify my code. When I was training, the error message was as follows
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/76981808/0092b7c9-da6b-49da-8884-88ed4d0a2ba8)

**Comment by tongfengqi** [comment]
This error should have nothing to do with the mask, but I don't know how to solve it

**Comment by cviviers** [comment]
Hi @tongfengqi,

The code uses the object initial bounding box width and height in the label files to determine optimal anchor box sizes. Do you have the widths and heights in your label files?

As for as the segmentation goes - yes they are optional, but from personal experience I saw the model generalizes much better if you can train with changing the background.
