### ISSUE TITLE
label site

### ISSUE THREAD

**Issue by assia855** [cviviers/YOLOv5-6D-Pose#17]
Hello, 
thanks for sharing this project so interesting. I would like to create my own dataset,  on the tutorial you didn't mention the website to label the 6D pose.
thanks in advance.

**Comment by cviviers** [comment]
Hi @assia855,

Unfortunately there is no website. To make your own dataset is quite tricky.
You need to:

1. print the charuco board
2. take pictures of it to get the camera calibration parameters 
3. place your object at a know offset from the charuco board coordinate system
4. take pictures of it to project the 3D model of your object onto the scene
5. obtain the 2d coordinate of your objects 3d bounding box

Alternatively you can do it all in simulation as discussed in #9.

**Comment by assia855** [comment]
Hi @cviviers  thanks for your answer. From what I understand I can use [data_curation] to create the label of my dataset I just need to create first the 3D  model, to do that I should generate it with blender is that it?
Thanks so much for your help.

**Comment by cviviers** [comment]
yes, that is a good start. I would say create a simple object first (simple cube) and make sure you understand the full process before trying intricate objects. Alternatively, if you have an RGB-D camera, you can follow this tutorial to skip making 3D objects yourself - [https://github.com/F2Wang/ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools )

**Comment by assia855** [comment]
thanks a lot @cviviers  I will test that and update you with the results
