### ISSUE TITLE
charuco board 

### ISSUE THREAD

**Issue by assia855** [cviviers/YOLOv5-6D-Pose#18]
Hi @cviviers, could you please share the Charuco board you use in [create_dataset](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/create_dataset.ipynb) I'm struggling with mine. Even after changing the [detect_Charuco_pose_board](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/pose_utils.py#362) parameters from  **number_markers_x = 8, number_markers_y = 5**  to   **number_markers_x = 4, number_markers_y = 3**,  it only computes the pose for a few frames in my dataset. Additionally, when I test the poses of the frames I obtained in [Sanity check](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/create_dataset.ipynb) function, I get these kinds of poses.

![Screenshot from 2024-07-08 17-02-12](https://github.com/cviviers/YOLOv5-6D-Pose/assets/62453226/27b0580f-2ab1-4f37-81e4-e42cfc57caa7)

**Comment by cviviers** [comment]
Hi @assia855,

Some general tips:

- the size of the printed markers need to exactly match the size you have them in your charuco description. In my example everything is in meters. So a marker needs to be 0.04m or 4 cm.
- Using Gimp you can print to a specific size to make sure the data size matches the printed size
- the paper has to be completely flat (tape the paper to a board if need be)
- the more markers the better, but the bigger the better as well.
- make sure to get camera calibration parameters with a board that matches the above description as well.
- it doesnt matter if some of the markers are not detected (the pose works under occlusions), as long as enough are detected (enough is relative :) )
- I printed on an A3 paper. If you have access to an A3 printer I can share my pdfs, but you should be able to create them using the provided code.

**Comment by assia855** [comment]
Hi @cviviers Thanks for all this suggestsion. 
- I measure manually  the size of my marker and I found 6cm, so I change the parameters in [detect_Charuco_pose_board](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/pose_utils.py#362) to **number_markers_x = 4, number_markers_y = 3, square_width = 0.07, aruco_width = 0.06** 
- For the order of markers where can I check it please and how can I fix it
- I make my paper completely flat and that helps me a lot in detecting more aruco and I have the pose for more frames than before now
- I get the camera calibration parameters with [calibrate.ipynb](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/calibrate.ipynb) and I think the pose is better than before but it still far from the real pose 
- I tried as well to play with **rotation_offset** and **translation_offset** but I still have this kind of pose

![Screenshot from 2024-07-09 12-42-30](https://github.com/cviviers/YOLOv5-6D-Pose/assets/62453226/7b0fcd44-0aa1-4d19-9458-19b7b23f4d5c)
![Screenshot from 2024-07-09 12-42-52](https://github.com/cviviers/YOLOv5-6D-Pose/assets/62453226/58dc628d-1aaa-432e-a305-1a5e18be679b)

**Comment by cviviers** [comment]
You need to print the exact pdf/png that is produced by the script. Do not cut the markers out and put them in different places or on a new piece of paper. The distance between markers also matters. Your latest pictures also seem like the paper is not flat enough. 

I think the offset you are referring to is the offset to the object from marker 1. Change this when you see the correct axis of the board in the corner of the board being displayed.

**Comment by assia855** [comment]
Hi @cviviers thanks  a lot for replay, I printed the charuco board and recompute the camera parameters with [calibrate.ipynb](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/calibrate.ipynb) this is the parameters that I got: `{"distortion": [-0.04745589091727264, 0.0004570602824454296, 0.012062003741561756, 0.008462426231645262, -1.1409376245420838e-06], "intrinsic": [[133.8815378174932, 0.0, 326.066571194312], [0.0, 81.07665840500025, 239.59919600396822], [0.0, 0.0, 1.0]]}` and after running [create_dataset.ipynb](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/create_dataset.ipynb) with the your  parameters this is the projection that I got: 

![Screenshot from 2024-07-10 12-29-33](https://github.com/cviviers/YOLOv5-6D-Pose/assets/62453226/94e1bdc0-95e6-437a-b538-c9d9119632c4)
![Screenshot from 2024-07-10 12-29-59](https://github.com/cviviers/YOLOv5-6D-Pose/assets/62453226/e92740ce-f69c-476a-8876-c6e7d4e175b8)

What can I fix as well to have the exact pose please? 

Thanks a lot for your help.

**Comment by cviviers** [comment]
what aruco dictionary did you use? remember since you created a custom board, you should use that custom board in all the other scripts as well. 

so for calibrate: instead of the current (# aruco_dict = Aruco.getPredefinedDictionary(Aruco.DICT_6X6_50) 
board = Aruco.CharucoBoard((8, 5), 0.5, 0.3, aruco_dict) ), use the board description you printed. 
the same holds for the create dataset.

I can already see you are only using Aruco.DICT_6X6_50, instead of the Aruco.DICT_6X6_250 used in the create_board script.

**Comment by assia855** [comment]
Hi @cviviers  thanks for the remark, yes actually you are right I didn't pay attention to that but actually in your code [calibrate](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/calibrate.ipynb) for the board you have: `board = Aruco.CharucoBoard((8, 5), 0.5, 0.3, aruco_dict)` and in [pose_utils](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/pose_utils.py) you have: `def detect_Charuco_pose_board(img, matrix_coefficients, distortion_coefficients, markerSize = 6, totalMarkers = 50, number_markers_x = 8, number_markers_y = 5, square_width = 0.05, aruco_width = 0.03) `what's the reason for this mismatch between the two scripts for **aruco_width** and **square_width** parameters.

1. I change in [calibrate](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/calibrate.ipynb) script : 
```
aruco_dict = Aruco.getPredefinedDictionary(Aruco.DICT_6X6_250) 
board = Aruco.CharucoBoard((10,10), 0.03, 0.02, aruco_dict)
```

Then the new camera parameters are:

- {"distortion": [-0.14586251322343352, 0.002714409119961078, -0.03316363613690248, -0.0301155824088724, 1.8753035462026414e-05], "intrinsic": [[218.72184535984664, 0.0, 375.74087853024554], [0.0, 312.4675978456318, 417.9311421430765], [0.0, 0.0, 1.0]]} 

2. I change in  [pose_utils](https://github.com/cviviers/YOLOv5-6D-Pose/blob/main/data_curation/pose_utils.py) the parameters in function **detect_Charuco_pose_board**: 

```
def detect_Charuco_pose_board(img, matrix_coefficients, distortion_coefficients, markerSize = 6, totalMarkers = 250, 
                            number_markers_x = 10, number_markers_y = 10, square_width = 0.03, aruco_width = 0.02)
```
but I still have this kind of projection: 

![Screenshot from 2024-07-10 15-59-04](https://github.com/cviviers/YOLOv5-6D-Pose/assets/62453226/effca587-36ad-4a70-bbef-efa013897ce9)

What I still doing wrong please?
Thanks a lot :)

**Comment by cviviers** [comment]
You do not have to use the same board to calibrate your camera and to eventually acquire data with. You can just use a standard checkerboard to calibrate the camera. In your implementation above, do you also use the` boardpts, num` from when you created the custom board in the follow up code? 

I think to ensure everything is well calibrated and to acquire the board pose correctly, lets start with the basic charuco board first (no cup included). From now on, use the board you describe here 
```
aruco_dict = Aruco.getPredefinedDictionary(Aruco.DICT_6X6_250) 
board = Aruco.CharucoBoard((10,10), 0.03, 0.02, aruco_dict) 
```
in all your scripts and also reprint it. It will have no hole in the middle but thats okay. 

This should give you the correct poses I believe.

**Comment by cviviers** [comment]
I will try to update the getting started code in the coming weeks to streamline the process. I think for people that are new to aruco markers and pose estimation there are quire some pitfalls. Your feedback helps a lot :)

**Comment by assia855** [comment]
Hi @cviviers  thanks for your answer, yes I use as well the `boardpts, num` to generate the charuco board. 

I follow your suggestion:

1. First I generate a charuco board without hole and use `calibrate.ipynb` to generate `camera_parameters.json` file 
2. Second I put my cup in the middle and estimate the` rotation and translation offset ` than I continue the process 
3. Third I remove ' **/1000** ' from  **vertices_og  = np.c_[np.array(mesh.vertices)/1000, np.ones((len(mesh.vertices), 1))].transpose() # vertices in object coordinate in meters**  in  the part  of load 3D model 

for the projection I got : 

![Screenshot from 2024-07-12 13-58-34](https://github.com/user-attachments/assets/1bb55324-440e-4082-846f-00f71b8eea08)

but for the mask I got: 

![Screenshot from 2024-07-12 14-12-34](https://github.com/user-attachments/assets/988d1b4a-7453-4d16-b72a-bcdfe39520f8)

Do the projection results indicate that my labeling are correct now? Could you please advise me on how to fix the mask issue?

Thanks for all your help.

**Comment by cviviers** [comment]
Very good, nice job getting the pose of the board. 
So the next part becomes a bit more tricky, the current code gives you this box and mask with which you can already train. However, it will likely not work well when deployed in a real world scenario. Do you have an accurate 3D model of the mug? If so, there are a few ways you can project that model onto the image to get an accurate mark

**Comment by assia855** [comment]
Hi @cviviers thanks a lot. Actually I launch train with this mask it trains and I have a detection on test image but I don't understand why I have `can't open/read file: check file path/integrity` in terminal while training, I'm missing some thing? should I register my data somewhere?
  
![Screenshot from 2024-07-15 12-22-02](https://github.com/user-attachments/assets/c092d485-80e6-465a-b1c3-1a6efc665e4f)

For the 3D model of the mug I got it from YCB-V dataset. I'm trying to find some codes to project the 3D on my 2D images but I'm not sure it is the good way to that or I should generate a 3D model of my real mug. I took the 3D mug of YCB-V dataset because it was similar to mu mug, clean and respect all the details that the neural needs. 

thanks so much for your help and illumination.

**Comment by cviviers** [comment]
This is a discrepancy between the windows and linux pathing convention I think. Somewhere either a `\` is being used when it should be a `/` Delete the cache files and check which file is not using the linux file pathing convention.

**Comment by assia855** [comment]
thanks @cviviers, 
I solve this issue effectively it was  just issue of `/` when I switched it the warning disappear.

**Comment by cviviers** [comment]
I recently thought of a nice method for you to get accurate enough masks if you do not have a good 3D model. You can just use the segment anything model [https://github.com/facebookresearch/segment-anything](https://github.com/facebookresearch/segment-anything) to set up a semi automatic segmentation of your objects. You can just prompt is with "cup" in each image and then check if it gives you good results.

**Comment by assia855** [comment]
Thanks @cviviers, actually for the mask I used track anything and I generate the masks then I launch a training with  it, here's the results. 
![Screenshot from 2024-07-22 13-37-31](https://github.com/user-attachments/assets/100e4ca1-f3c7-469d-8316-ea0388a1eab3)

but I don't know if the rotation and the translation  of the object  is correct or not ?

**Comment by cviviers** [comment]
If you run the test.py instead of detect.py it will draw the ground truth points as well if you have them

**Comment by assia855** [comment]
Hi @cviviers  I run test.py and it create an empty  folder in test I don't understand why ? 

![Screenshot from 2024-07-22 15-40-31](https://github.com/user-attachments/assets/a334484a-3f42-4493-b8a0-073c34f83910)

Thanks a lot for your help!

**Comment by cviviers** [comment]
You have to pass the flag `--test-plotting` when running test.py. Please check the code

**Comment by assia855** [comment]
thanks @cviviers  for your remark. Actually now I have the images with two boxes blue and green but no mesh. Why I don't have the projection of the mesh ? 

![Screenshot from 2024-07-22 17-38-14](https://github.com/user-attachments/assets/c7d1ea39-af9b-4eed-8a47-811ae1ce2e12)

**Comment by cviviers** [comment]
The current code does not do that, since we were interested in obtaining the pose using the keypoints. Feel free to extend the code to your needs :) 

With this I think you've learnt a lot and completed what your current Github issue set out to do. Congrats! Feel free to open a new issue if you have any more problems with the current code.
