### ISSUE TITLE
How can I get the coordinates of corner points in camera coordinate system?

### ISSUE THREAD

**Issue by tongfengqi** [cviviers/YOLOv5-6D-Pose#19]
Hello,

I hope this message finds you well. I successfully reproduced your project on my dataset and obtained the pixel coordinates of the target object's eight corner points. Could you kindly guide me on how to convert these pixel coordinates to the camera coordinate system?

Thank you for your time and for your excellent work on this project.

**Comment by cviviers** [comment]
Hey @tongfengqi,

The rotation and translation matrices are computed from the 2D correspondence [here](https://github.com/cviviers/YOLOv5-6D-Pose/blob/6b982c6043bb41ab53da804e8d09300ed5204261/test.py#L223). How you want to display these or what you want to do with them are up to you. :)

**Comment by tongfengqi** [comment]
@cviviers The [R | t] obtained through pnp can convert the coordinates of points in the PLY file to the camera coordinate system. I don't know if I understand correctly or not. 
But what I want is the coordinates of the eight corners of this object in real space in the camera coordinate system, not the coordinates of the points in the PLY file in the camera coordinate system.
My current idea is to combine the size information of the target object, camera intrinsic parameters, and pixel coordinates of the eight corner points to calculate the camera coordinate system coordinates of these eight corner points. May I ask if my method is feasible, or if there are any other methods available？
