### ISSUE TITLE
This is an existing study

### ISSUE THREAD

**Issue by gu-qsw** [cviviers/YOLOv5-6D-Pose#2]
Published on the 2021 IEEE as mfpn-6d![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/127026384/e6645046-7d26-4548-9dd9-368b9f830bb6)

**Comment by gu-qsw** [comment]
![image](https://github.com/cviviers/YOLOv5-6D-Pose/assets/127026384/11cf02e2-29b7-4bdb-a934-b82b42986f97)

**Comment by cviviers** [comment]
Hi @gu-qsw,

Thanks for pointing to this work. Do you know if there is code available? Also if the paper is publicly accessible? I would appreciate it if you can send me the work at c.g.a.viviers@tue.nl 

From the snippet here I can see our research takes a different direction to this paper. We focus on variable acquisition geometry and a specific application in X-ray images and medical instrument 6-DoF pose estimation. 

I think the community will appreciate this line of research being publicly available.

**Comment by gu-qsw** [comment]
@cviviers 

Please check the mail

**Comment by cviviers** [comment]
Thanks again for pointing out this work. As we discussed, there are some significant differences between the mentioned work and our proposed approach, including the model objective, its application and finally overall improved performance. 

Please keep an eye out on the full paper and code to be released soon :)
