### ISSUE TITLE
Paper on ARXIV

### ISSUE THREAD

**Issue by gautam1858** [cviviers/YOLOv5-6D-Pose#3]
Hi,

Can you please make the paper accessible on arxiv ?

-GR

**Comment by gautam1858** [comment]
@cviviers Can you please help ?

**Comment by cviviers** [comment]
Hi @gautam1858, 
The paper was published with closed access. I am trying to see if I am allowed to publish on arxiv and under what conditions.
Will update the readme if I can upload it.

**Comment by gautam1858** [comment]
Thank you, looking forward to it 👍🏽

**Comment by cviviers** [comment]
Hey @gautam1858, 

I was able to upload an early author version of the paper to [arxiv](https://arxiv.org/abs/2405.11677v1). It is slightly different from the published paper but feel free to reach out if you have any questions.
