### ISSUE TITLE
when I train the model, the error below happened. And I fail to build the compute_overlap.pyx

### ISSUE THREAD

**Issue by tongfengqi** [cviviers/YOLOv5-6D-Pose#4]
Traceback (most recent call last):
  File "D:\chorme\yolov5-6d-pose\train.py", line 546, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "D:\chorme\yolov5-6d-pose\train.py", line 217, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "D:\chorme\yolov5-6d-pose\utils\datasets.py", line 67, in create_dataloader
    dataset = LoadImagesAndLabelsPose(path, imgsz, batch_size,
  File "D:\chorme\yolov5-6d-pose\utils\datasets.py", line 537, in __init__
    assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels.'
AssertionError: train: No labels in ..\data\LINEMOD\benchvise\train.cache. Can not train without labels.

**Comment by cviviers** [comment]
Hi @tongfengqi,

The code indexes (creates some cache file) the first time it runs. It seems there are no labels in the cache file it created. Delete the train.cache file and run it again and check that there are no errors the first time it runs. It should say that for every image a corresponding label was found.

As for the compute_overlap.pyx file, what error are you getting? You need a few things to build the file

**Comment by cviviers** [comment]
@tongfengqi any luck? let me know if I can help

**Comment by tongfengqi** [comment]
Thank you very much for your patient reply. Both the test and train sections have been successfully completed. 
I want to create my own dataset now, and I noticed that the CreatingDataset.md file says "Our label files include 21 ground truth values", but I found that the label files of the objects in the linemod dataset all contain 29 numbers. It is also mentioned that "Each of the 21 numbers corresponding to specific data points", but I did not find the Object rotation vector (Rodriques) [3x1] and Object translation vector [3x1] in the label file of linemod. Can you explain in detail how to create my own dataset, including label files? Thank you very much!
![63b76078-35b9-4ff0-8726-680324ee81de](https://github.com/cviviers/YOLOv5-6D-Pose/assets/76981808/19633952-d8f3-45ae-977f-db758bd6fe98)

**Comment by flashmoment** [comment]
> @tongfengqi any luck? let me know if I can help



> Hi @tongfengqi,
> 
> The code indexes (creates some cache file) of your data the first time it runs. It seems there are no labels in the cache file it created. Delete the train.cache file and run it again and check that there are no errors the first time it runs. It should say that for every image a corresponding label was found.
> 
> As for the compute_overlap.pyx file, what error are you getting? You need a few things to build the file



> Hi @tongfengqi,
> 
> The code indexes (creates some cache file) of your data the first time it runs. It seems there are no labels in the cache file it created. Delete the train.cache file and run it again and check that there are no errors the first time it runs. It should say that for every image a corresponding label was found.
> 
> As for the compute_overlap.pyx file, what error are you getting? You need a few things to build the file

Hello, I deleted the .cache file, and then I reran train.py, but I still got the same error.

**Comment by flashmoment** [comment]
> @cviviers Thank you very much for your patient reply. Both the test and train sections have been successfully completed. I want to create my own dataset now, and I noticed that the CreatingDataset.md file says "Our label files include 21 ground truth values", but I found that the label files of the objects in the linemod dataset all contain 29 numbers. It is also mentioned that "Each of the 21 numbers corresponding to specific data points", but I did not find the Object rotation vector (Rodriques) [3x1] and Object translation vector [3x1] in the label file of linemod. Can you explain in detail how to create my own dataset, including label files? Thank you very much! ![63b76078-35b9-4ff0-8726-680324ee81de](https://private-user-images.githubusercontent.com/76981808/331513036-19633952-d8f3-45ae-977f-db758bd6fe98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjU1MTQsIm5iZiI6MTcxNjE2NTIxNCwicGF0aCI6Ii83Njk4MTgwOC8zMzE1MTMwMzYtMTk2MzM5NTItZDhmMy00NWFlLTk3N2YtZGI3NThiZDZmZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAwMzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGU0Y2UzMDc3OTQ0Njk1NjA5N2VhZjdhOTVmZDY5MGJmMmRkZjM2NmRjNTJlNmE1MGU0NjBlNDc4NzM1NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9PcwymGUpQHrlfDofyF9glthj942mQyNYgvCjwakzA0)

Can you take a look at the output in your terminal during training? I think there might be some issues with my output.

**Comment by cviviers** [comment]
@tongfengqi can I close this issue?

**Comment by tongfengqi** [comment]
@cviviers Of course, thank you for your help.
