### ISSUE TITLE
image miss lables and no masks found

### ISSUE THREAD

**Issue by hippohi** [cviviers/YOLOv5-6D-Pose#5]
hi dear author ,i tried to run test.py then i got this:
Fusing layers... 
Model Summary: 391 layers, 97574820 parameters, 0 gradients, 225.4 GFLOPS
val: Scanning 'D:\data\LINEMOD\cat\labels' for images, labels and masks... 1179 found, 0 missing, 0 empty, 0 corrupted, 0 found, 1179 missing, 0 empty, 0 corrupted: 100%|██████████| 1179/1179 [00:01<00:00, 1101.94it/s]
val: WARNING: No masks found in D:\data\LINEMOD\cat\labels.cache.

i dont know why the lables are all missing and are those masks  scanned automatically just like the lables?
besides "--rect" and "--cache" aren`t existing in parser.add_argument so i deleted them.

**Comment by cviviers** [comment]
Hey @hippohi,

Could it be that in a previous run, when the cache was created, there was something else wrong? Do you mind deleting the cache file and running it again? There will be explicit error messages if anything is indeed wrong.

**Comment by hippohi** [comment]
> Hey @hippohi,
> 
> Could it be that in a previous run, when the cache was created, there was something else wrong? Do you mind deleting the cache file and running it again? There will be explicit error messages if anything is indeed wrong.


hey my friend helped me solve the issue ! If you run the train.py on WINDOWS,you may need to change the "replace('/00', '/')" into "replace('\\00', '\\')"  which is located under the function "def Linemodimg2mask_paths(img_paths):" of dataset.py.
