### ISSUE TITLE
Where is Mesh Data?

### ISSUE THREAD

**Issue by caichuang0415** [cviviers/YOLOv5-6D-Pose#6]
Thanks for sharing your codes.
I see there is a argument called mesh-data, and the example infer command you give, the mesh data is "--mesh-data path/to/data/LINEMOD/cat/cat.ply".
but I could not find a cat.ply file, I wonder how can I get these .ply files, thank you

**Comment by cviviers** [comment]
Hey @caichuang0415 

The mesh data/.ply files are saved together with the data of each object. You can download it [here](https://drive.google.com/drive/folders/13pkdF4KpqXWXbEIkiAcHoO-YUr_CWN-L?usp=drive_link). I will update the getting started notebook in a couple of days with some more details for future users.

Hope it helps
