### ISSUE TITLE
About dataset structure

### ISSUE THREAD

**Issue by dionstew** [cviviers/YOLOv5-6D-Pose#8]
I am interested to this project and looking forward to implement the architecture using my dataset. I would like to know the dataset structure and the file it contains, if it is okay to share...

**Comment by cviviers** [comment]
Hi @dionstew,

The linemod dataset used in this work is a good example to start with. If you want to use it on your own data we provide some [tools ](https://github.com/cviviers/YOLOv5-6D-Pose/tree/main/data_curation) to get you going (I will improve these soon) . Additionally you can follow the code  [here](https://github.com/Microsoft/singleshotpose/blob/master/label_file_creation.md).

Let me know if you have some specific question about the data curation.

**Comment by dionstew** [comment]
Hi again, thanks for the help.

Is 3d model data required? In my work, I try to estimate 6D poses on objects that do not necessarily have the exact same shape and size such as human body parts.

**Comment by cviviers** [comment]
For this line of work, yes, you do require some 3D model. Although you can likely change the model at test time if the object **only** varies in size (to be tested).  However, I think what you are looking for might rather be something like [human mesh recovery](https://github.com/naver/multi-hmr) if you are planning on working with body parts.

**Comment by cviviers** [comment]
@dionstew can I close this issue? I assume the above mentioned line of work is more suitable for you.
